/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rms;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class bill extends javax.swing.JFrame {

    /**
     * Creates new form bill
     */
    public bill() {
        initComponents();
        
    }
    
        Connection con;
        PreparedStatement pst;
        ResultSet rs;
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        itcd = new javax.swing.JLabel();
        itname = new javax.swing.JLabel();
        qty = new javax.swing.JLabel();
        prc = new javax.swing.JLabel();
        tt = new javax.swing.JLabel();
        itemcodeetxt = new javax.swing.JTextField();
        itemnameetxt = new javax.swing.JTextField();
        priceetxt = new javax.swing.JTextField();
        tottxt = new javax.swing.JTextField();
        qtyytxt = new javax.swing.JSpinner();
        addbt = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totall = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        payy = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        balann = new javax.swing.JTextField();
        printbillb = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        itcd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itcd.setForeground(new java.awt.Color(255, 255, 255));
        itcd.setText("ItemCode");

        itname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itname.setForeground(new java.awt.Color(255, 255, 255));
        itname.setText("ItemName");

        qty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qty.setForeground(new java.awt.Color(255, 255, 255));
        qty.setText("Quantity");

        prc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        prc.setForeground(new java.awt.Color(255, 255, 255));
        prc.setText("Price");

        tt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tt.setForeground(new java.awt.Color(255, 255, 255));
        tt.setText("Total");

        itemcodeetxt.setBackground(new java.awt.Color(0, 0, 0));
        itemcodeetxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemcodeetxt.setForeground(new java.awt.Color(255, 255, 51));
        itemcodeetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemcodeetxtKeyPressed(evt);
            }
        });

        itemnameetxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemnameetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnameetxtActionPerformed(evt);
            }
        });

        priceetxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        tottxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        qtyytxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        qtyytxt.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qtyytxtStateChanged(evt);
            }
        });

        addbt.setBackground(new java.awt.Color(0, 102, 102));
        addbt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addbt.setForeground(new java.awt.Color(255, 255, 255));
        addbt.setText("ADD");
        addbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(itcd)
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addComponent(itemcodeetxt))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemnameetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itname))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qty)
                    .addComponent(qtyytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prc))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tt)
                    .addComponent(tottxt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addbt)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itcd)
                    .addComponent(itname)
                    .addComponent(qty)
                    .addComponent(prc)
                    .addComponent(tt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemcodeetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemnameetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tottxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(addbt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 630, 190));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Total");

        totall.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Pay");

        payy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Balance");

        balann.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        printbillb.setBackground(new java.awt.Color(0, 102, 102));
        printbillb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        printbillb.setForeground(new java.awt.Color(255, 255, 255));
        printbillb.setText("PRINT BILL");
        printbillb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbillbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totall, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(payy)
                    .addComponent(balann))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(printbillb, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balann, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printbillb)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 220, 220));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemCode", "ItemName", "Quantity", "Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 630, 310));

        txtbill.setColumns(20);
        txtbill.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtbill.setRows(5);
        jScrollPane2.setViewportView(txtbill);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 220, 280));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemnameetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnameetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemnameetxtActionPerformed

    private void itemcodeetxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemcodeetxtKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
        String icode = itemcodeetxt.getText();
        
            try {
                Class.forName("com.mysql.jdbc.Driver");
                
                con = DriverManager.getConnection("jdbc:mysql://localhost/Food", "root", "");
                pst = con.prepareStatement("SELECT * from fooditems WHERE ItemCode = ? ");
                        
                 pst.setString(1,icode); 
                 rs = pst.executeQuery();
                 
                 if(rs.next() == false) 
                 {
                 
                     JOptionPane.showMessageDialog(this, "ItemCode not found");
                 
                 }
                 else 
                 {
                 
                     String iname = rs.getString("ItemName");
                     String pri = rs.getString("Price");
                     
                    itemnameetxt.setText(iname.trim());
                    priceetxt.setText(pri.trim());    
                     
                     
                 }
                     
                   
          
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_itemcodeetxtKeyPressed

    private void qtyytxtStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qtyytxtStateChanged
        // TODO add your handling code here:
        
        int qty = Integer.parseInt(qtyytxt.getValue().toString());
        int pri = Integer.parseInt(priceetxt.getText());
        
        int tot;
        tot = qty * pri;
        
        tottxt.setText(String.valueOf(tot));
        
    }//GEN-LAST:event_qtyytxtStateChanged

    
    public void Balance()
    {
    
        int tota = Integer.parseInt(totall.getText());
        int pay = Integer.parseInt(payy.getText());
        
        int bal;
        bal = pay - tota;
        
        balann.setText(String.valueOf(bal));
    
    }
    
    public void bill()
    {
    
    String total = totall.getText();
    String pay = payy.getText();
    String bal = balann.getText();
    
    DefaultTableModel model = new DefaultTableModel();
        
    model = (DefaultTableModel)jTable1.getModel();
    
    txtbill.setText(txtbill.getText() + "***************************************\n");
    txtbill.setText(txtbill.getText() + "            BILL\n");
    txtbill.setText(txtbill.getText() + "***************************************\n");
    
    //heading
    txtbill.setText(txtbill.getText() + "PRODUCT" + "\t" + "PRICE" + "\t" + "TOTAL" + "\n");
    
    for(int i = 0; i < model.getRowCount(); i++)
    {
    
        String iname = (String)model.getValueAt(i, 1);
        String price = (String)model.getValueAt(i, 3);
        String tota = (String)model.getValueAt(i, 4);
    
     txtbill.setText(txtbill.getText() + iname + "\t" + price + "\t" + tota + "\n");   
        
    
    }
    
    
    txtbill.setText(txtbill.getText() + "\n");
    
    txtbill.setText(txtbill.getText() + "\t" + "\t" + "SUBTOTAL : " + total + "\n");
    txtbill.setText(txtbill.getText() + "\t" + "\t" + "PAY : " + pay + "\n");
    txtbill.setText(txtbill.getText() + "\t" + "\t" + "BALANCE : " + bal + "\n");
    txtbill.setText(txtbill.getText() + "\n");
    txtbill.setText(txtbill.getText() + "***************************************\n");
    txtbill.setText(txtbill.getText() + "THANK YOU! COME AGAIN\n");
    
    }
    
    
    
    private void addbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = new DefaultTableModel();
        
        model = (DefaultTableModel)jTable1.getModel();

        model.addRow(new Object[]
                
        {
        
            itemcodeetxt.getText(),
            itemnameetxt.getText(),
            qtyytxt.getValue().toString(),
            priceetxt.getText(),
            tottxt.getText(),
         
        });
        
        int sum = 0;
        
        for(int i = 0; i<jTable1.getRowCount(); i++ )
            
        {
        
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 4).toString());
        
        }  
            
        totall.setText(Integer.toString(sum));
        
        itemcodeetxt.setText("");
        itemnameetxt.setText("");
        priceetxt.setText("");
        tottxt.setText("");
        itemcodeetxt.requestFocus();
       
        
    }//GEN-LAST:event_addbtActionPerformed

    private void printbillbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbillbActionPerformed
        // TODO add your handling code here:
        
        Balance();
        bill();
    }//GEN-LAST:event_printbillbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbt;
    private javax.swing.JTextField balann;
    private javax.swing.JLabel itcd;
    private javax.swing.JTextField itemcodeetxt;
    private javax.swing.JTextField itemnameetxt;
    private javax.swing.JLabel itname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField payy;
    private javax.swing.JLabel prc;
    private javax.swing.JTextField priceetxt;
    private javax.swing.JButton printbillb;
    private javax.swing.JLabel qty;
    private javax.swing.JSpinner qtyytxt;
    private javax.swing.JTextField totall;
    private javax.swing.JTextField tottxt;
    private javax.swing.JLabel tt;
    private javax.swing.JTextArea txtbill;
    // End of variables declaration//GEN-END:variables

    
}
